# 推送通知相关配置
notification:
  url: http://10.0.91.189:19101//verse-service/ping/VIID/SubscribeNotifications

logging:
  path: ./log

kafka:
  servers:
    - 10.0.91.88:9092
    - 10.0.91.88:9092
  groupId: motor-vehicle-gyjg